name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9, 3.10, 3.11]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.1.1
      with:
        submodules: 'true'

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install poetry
        poetry install

    - name: Run static type checking (mypy)
      run: poetry run mypy pydicom_seg --exclude pydicom_seg/external

    - name: Run test suite (pytest)
      run: poetry run pytest tests/
